const fs = require('fs');
let text = fs.readFileSync('app.js', 'utf8');

function replaceBlock(startMarker, endMarker, replacement) {
  const start = text.indexOf(startMarker);
  if (start === -1) throw new Error('Missing start marker: ' + startMarker);
  const end = text.indexOf(endMarker, start);
  if (end === -1) throw new Error('Missing end marker: ' + endMarker);
  text = text.slice(0, start) + replacement.trimEnd() + '\n\n' + text.slice(end);
}

const fillSupplierSelectBlock = [
  "function fillSupplierSelect() {",
  "  const e = el('apSupplier'); if (!e) return;",
  "  const cur = e.value;",
  "  e.innerHTML = '<option value=\"\">— بەبێ فرۆشیار —</option>'",
  "    + getSuppliers().map(s => `<option value=\"${s.name}\">${s.name}</option>`).join('');",
  "  if (cur) e.value = cur;",
  "}",
].join('\n');

const renderLowStockBannerBlock = [
  "function renderLowStockBanner() {",
  "  const low = getLowStockProducts(5);",
  "  const b = el('lowStockBanner'); if (!b) return;",
  "  if (!low.length) { b.innerHTML = ''; return; }",
  "  b.innerHTML = `<div class=\"stock-alert\" onclick=\"showPage('products')\">` +",
  "    `⚠️ ${low.length} کاڵا ستۆکیان کەمە: ${low.map(p => {` +",
  "      `const st = getProductStats(p.id);` +",
  "      `return `<strong>${escHtml(p.name)}</strong> (${fmtN(st.stockQty,2)} ${escHtml(p.unit)})`;` +",
  "    `}).join('، ')}` +",
  "  `</div>`;",
  "}",
].join('\n');

const renderDebtDueBannerBlock = [
  "function renderDebtDueBanner() {",
  "  const b = el('debtDueBanner'); if (!b) return;",
  "  const alerts = getDebtDueAlerts();",
  "  if (!alerts.length) { b.innerHTML = ''; return; }",
  "",
  "  const overdues = alerts.filter(a => a.status === 'overdue');",
  "  const soons = alerts.filter(a => a.status === 'soon');",
  "",
  "  let html = '';",
  "  if (overdues.length) {",
  "    html += `<div class=\"debt-due-banner overdue\" onclick=\"showPage('products')\">",
  "      <span class=\"ddb-icon\">⏰</span>",
  "      <div class=\"ddb-body\">",
  "        <div class=\"ddb-title\">${overdues.length} قەرزدار بەرواریان تێپەڕیوە!</div>",
  "        <div class=\"ddb-names\">${overdues.map(a =>",
  "          `<span class=\"ddb-name\">${escHtml(a.name)} · ${fmtC(a.owedUSD,'USD')}</span>`",
  "        ).join('')}</div>",
  "      </div>",
  "    </div>`;",
  "  }",
  "  if (soons.length) {",
  "    html += `<div class=\"debt-due-banner soon\" onclick=\"showPage('products')\">",
  "      <span class=\"ddb-icon\">📅</span>",
  "      <div class=\"ddb-body\">",
  "        <div class=\"ddb-title\">${soons.length} قەرزدار بەرواریان نزیکە (لە ماوەی 7 ڕۆژ)</div>",
  "        <div class=\"ddb-names\">${soons.map(a =>",
  "          `<span class=\"ddb-name\">${escHtml(a.name)} · ${a.diffDays === 0 ? 'ئەمڕۆ!' : a.diffDays + ' ڕۆژ'}</span>`",
  "        ).join('')}</div>",
  "      </div>",
  "    </div>`;",
  "  }",
  "  b.innerHTML = html;",
  "}",
].join('\n');

const renderDashBlock = [
  "function renderDash() {",
  "  renderLowStockBanner();",
  "  renderDebtDueBanner();",
  "  const prods = getProducts();",
  "  const g = getGlobalStats();",
  "  const now = new Date();",
  "  const y = now.getFullYear(), m = now.getMonth() + 1;",
  "  const mPad = String(m).padStart(2, '0');",
  "  const mp = getProfitByRange(`${y}-${mPad}-01`, endOfMonth(y, m));",
  "",
  "  el('dashStats').innerHTML = `",
  "    <div class=\"scard info\"><div class=\"si\">📦</div><div class=\"sv\" style=\"color:var(--info)\">${prods.length}</div><div class=\"sl\">کاڵاکان</div></div>",
  "    <div class=\"scard ok\"><div class=\"si\">💰</div><div class=\"sv tok\">${fmtC(g.totalRevenueUSD,'USD')}</div><div class=\"sl\">کۆی فرۆشتن</div></div>",
  "    <div class=\"scard bad\"><div class=\"si\">💸</div><div class=\"sv tbad\">${fmtC(g.soldCostUSD,'USD')}</div><div class=\"sl\">تێچووی فرۆشراو</div></div>",
  "    <div class=\"scard ${g.debtRemainUSD>0?'bad':'ok'}\"><div class=\"si\">💳</div><div class=\"sv ${g.debtRemainUSD>0?'tbad':'tok'}\">${fmtC(g.debtRemainUSD,'USD')}</div><div class=\"sl\">قەرزی ماوە</div></div>",
  "    <div class=\"scard ${g.profitUSD>=0?'ok':'bad'}\">",
  "      <div class=\"si\">${g.profitUSD>=0?'📈':'📉'}</div>",
  "      <div class=\"sv ${g.profitUSD>=0?'tok':'tbad'}\">${fmtC(g.profitUSD,'USD')}</div>",
  "      <div class=\"sl\">${g.profitUSD>=0?'قازانج':'زەرەر'}</div>",
  "    </div>",
  "    <div class=\"scard info\"><div class=\"si\">📦</div><div class=\"sv\" style=\"color:var(--info)\">${fmtC(g.remainingStockValueUSD,'USD')}</div><div class=\"sl\">نرخی ستۆک</div></div>`;",
  "",
  "  const todayStr = today();",
  "  const tp = getProfitByRange(todayStr, todayStr);",
  "",
  "  el('dashMonthProfit').innerHTML = `",
  "    <div style=\"margin-bottom:10px;padding:10px;background:var(--bg3);border-radius:var(--rs);text-align:center\">",
  "      <div style=\"font-size:10px;color:var(--muted);margin-bottom:4px;font-weight:600;text-transform:uppercase;letter-spacing:.5px\">ئەمڕۆ</div>",
  "      <div style=\"font-size:18px;font-weight:800;color:${tp.revenueUSD>0?'var(--ok)':'var(--muted)'}\">${tp.revenueUSD>0?fmtC(tp.revenueUSD,'USD'):'هیچ فرۆشتنێک نییە'}</div>",
  "      ${tp.revenueUSD>0?`<div style=\"font-size:10px;color:var(--muted);margin-top:2px\">${tp.profitUSD>=0?'📈':'📉'} ${fmtC(tp.profitUSD,'USD')} ${tp.profitUSD>=0?'قازانج':'زەرەر'}</div>`:''}",
  "    </div>",
  "    <div class=\"sum-box\" style=\"padding:12px\">",
  "      <div class=\"sum-row\"><span class=\"lbl\">💰 کۆی فرۆشتن</span><span class=\"val tok\">${fmtC(mp.revenueUSD,'USD')}</span></div>",
  "      <div class=\"sum-row\"><span class=\"lbl\">💸 کۆی تێچوو</span><span class=\"val tbad\">${fmtC(mp.costUSD,'USD')}</span></div>",
  "      <div class=\"sum-total\"><span>${mp.profitUSD>=0?'📈 قازانج':'📉 زەرەر'}</span>",
  "        <span class=\"${mp.profitUSD>=0?'tok':'tbad'} fw8\">${fmtC(mp.profitUSD,'USD')}</span>",
  "      </div>",
  "    </div>`;",
  "",
  "  const allEvs = getAllEvents();",
  "  const debtorMap = {};",
  "  allEvs.forEach(ev => {",
  "    const token = ev.customerToken || makeCustomerToken(ev.buyer || '', ev.phone || '');",
  "    if (ev.type === 'sell_debt') {",
  "      if (!debtorMap[token]) {",
  "        const reg = lookupCustomerByToken(token);",
  "        debtorMap[token] = {",
  "          name: reg?.name || ev.buyer || 'نەناسراو',",
  "          phone: reg?.phone || ev.phone || '',",
  "          token,",
  "          totalUSD: 0,",
  "          products: new Set(),",
  "        };",
  "      }",
  "      debtorMap[token].totalUSD += toUSD(ev.totalPrice, ev.currency);",
  "      const prod = getProduct(ev.productId);",
  "      if (prod) debtorMap[token].products.add(prod.name);",
  "    }",
  "    if (ev.type === 'debt_pay' && debtorMap[token]) {",
  "      debtorMap[token].totalUSD -= toUSD(ev.amount, ev.currency);",
  "    }",
  "  });",
  "  const debtors = Object.values(debtorMap).map(d => ({ ...d, totalUSD: Math.max(0, roundMoney(d.totalUSD)) })).filter(d => d.totalUSD > 0.001);",
  "",
  "  el('dashDebt').innerHTML = debtors.length",
  "    ? debtors.sort((a, b) => b.totalUSD - a.totalUSD).map(d => {",
  "        const link = getDebtorLink(d.name, d.phone);",
  "        const waMsg = encodeURIComponent(`سڵاو ${d.name} 👋\\nقەرزەکەت: ${fmtC(d.totalUSD,'USD')}\\nبینینی مامەڵەکانت:\\n${link}`);",
  "        const waLink = d.phone ? `https://wa.me/${d.phone.replace(/\\D/g,'')}?text=${waMsg}` : '';",
  "        return `<div style=\"padding:9px 0;border-bottom:1px solid var(--border)\">",
  "          <div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:6px\">",
  "            <div>",
  "              <div style=\"font-size:13px;font-weight:600\">${escHtml(d.name)}</div>",
  "              <div style=\"font-size:11px;color:var(--muted)\">${d.phone?`📞 <a href=\"tel:${escHtml(d.phone)}\" style=\"color:var(--primary);text-decoration:none\">${escHtml(d.phone)}</a> · `:''}${[...d.products].map(n=>escHtml(n)).join('، ')}</div>",
  "            </div>",
  "            <span class=\"tbad fw8\">${fmtC(d.totalUSD,'USD')}</span>",
  "          </div>",
  "          <div style=\"display:flex;gap:5px;flex-wrap:wrap\">",
  "            <button class=\"btn btn-xs btn-g\" onclick=\"copyLink('${link}')\">🔗 لینک</button>",
  "            ${waLink?`<a href=\"${waLink}\" target=\"_blank\" class=\"btn btn-xs\" style=\"background:#25d366;color:#fff;text-decoration:none;display:inline-flex;align-items:center;gap:4px\">واتساپ</a>`:''}",
  "          </div>",
  "        </div>`;",
  "      }).join('')",
  "    : `<div class=\"empty\"><span class=\"ei\">✅</span>هیچ قەرزێک نییە</div>`;",
  "",
  "  const top = prods.map(p => ({ ...p, ...getProductStats(p.id) })).sort((a, b) => b.profitUSD - a.profitUSD).slice(0, 5);",
  "  const maxProfit = top.length ? Math.max(...top.map(p => Math.abs(p.profitUSD)), 1) : 1;",
  "  el('dashTopProds').innerHTML = top.length",
  "    ? top.map((p, i) => {",
  "        const pct = Math.round((Math.abs(p.profitUSD) / maxProfit) * 100);",
  "        const isPos = p.profitUSD >= 0;",
  "        return `<div style=\"padding:8px 0;border-bottom:1px solid var(--border)\">",
  "          <div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:5px\">",
  "            <div style=\"display:flex;align-items:center;gap:8px\">",
  "              <span style=\"width:20px;height:20px;border-radius:50%;background:${isPos?'var(--ok-bg)':'var(--bad-bg)'};display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:800;color:${isPos?'var(--ok)':'var(--bad)'};flex-shrink:0\">${i+1}</span>",
  "              <div>",
  "                <div style=\"font-size:13px;font-weight:700\">${escHtml(p.name)}</div>",
  "                <div style=\"font-size:10px;color:var(--muted)\">${fmtN(p.stockQty,2)} ${escHtml(p.unit)} مانەوە</div>",
  "              </div>",
  "            </div>",
  "            <span class=\"${isPos?'tok':'tbad'} fw8\" style=\"font-size:12px\">${fmtC(p.profitUSD,'USD')}</span>",
  "          </div>",
  "          <div style=\"height:4px;background:var(--bg3);border-radius:2px;overflow:hidden\">",
  "            <div style=\"height:100%;width:${pct}%;background:${isPos?'var(--ok)':'var(--bad)'};border-radius:2px;transition:width .5s ease\"></div>",
  "          </div>",
  "        </div>`;",
  "      }).join('')",
  "    : `<div class=\"empty\"><span class=\"ei\">📦</span>هیچ کاڵایەک نییە<br><button class=\"btn btn-p btn-sm mt8\" onclick=\"showPage('addProduct')\">➕ زیادبکە</button></div>`;",
  "",
  "  const newHash = `${prods.length}|${allEvs.length}|${_statsCacheVersion}|${chartMonthRange}`;",
  "  if (newHash !== _lastChartHash) {",
  "    _lastChartHash = newHash;",
  "    setTimeout(() => renderCharts(), 50);",
  "  }",
  "}",
].join('\n');

replaceBlock('function fillSupplierSelect() {', 'function renderLowStockBanner() {', fillSupplierSelectBlock);
replaceBlock('function renderLowStockBanner() {', 'function renderDebtDueBanner() {', renderLowStockBannerBlock);
replaceBlock('function renderDebtDueBanner() {', 'function renderDash() {', renderDebtDueBannerBlock);
replaceBlock('function renderDash() {', '// ============================================================\n// ===== CHARTS =====', renderDashBlock);

fs.writeFileSync('app.js', text, 'utf8');
